# Drone CI File!

kind: pipeline
type: kubernetes
name: build er-web

node_selector:
  doks.digitalocean.com/node-pool: josa-cloud-np

steps:
  - name: build and release er-web
    image: plugins/docker
    settings:
      repo: josaorg/er-web
      build_args:
        [
          MATOMO_SITE_ID=4,
          OTS_FORM_LINK=https://ots.josa.ngo/assets/form/form.js,
          OTS_CHAT_LINK=https://ots.josa.ngo/assets/chat/chat.min.js,
          TARGET_ENV=production,
          ONION_ADDRESS=http://pqkxrgh4cngoearb3fbr5sfpoouapjap3qm7mnhk6oa3dv6expxbreqd.onion,
        ]
      build_args_from_env:
        [
          DRONE_BUILD_NUMBER,
          DRONE_BUILD_LINK,
          DRONE_COMMIT_SHA,
          DRONE_COMMIT_LINK,
          DRONE_REPO_LINK,
          DRONE_BUILD_FINISHED,
        ]
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: false
  - name: notify on Slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: heartbeat
    depends_on:
      - build and release er-web
