# Drone CI File!

kind: pipeline
type: kubernetes
name: build er-web

node_selector:
  doks.digitalocean.com/node-pool: josa-cloud-np

steps:
  - name: build and release er-web
    image: plugins/docker
    settings:
      repo: josaorg/er-web
      build_args:
        [
          MATOMO_SITE_ID=9,
          OTS_FORM_LINK=https://ots.josa.ngo/assets/form/form.js,
        ]
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: false
  - name: notify on Slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: heartbeat
    depends_on:
      - build and release er-web
