# set global args
ARG NODE_ENV=development HOST=0.0.0.0 PORT=3000 USER=node MATOMO_SITE_ID=9 OTS_FORM_LINK=https://ots.josa.ngo/assets/form/form.js TARGET_ENV DRONE_COMMIT_SHA=${DRONE_COMMIT_SHA} DRONE_BUILD_NUMBER=${DRONE_BUILD_NUMBER} DRONE_BUILD_LINK=${DRONE_BUILD_LINK} DRONE_COMMIT_LINK=${DRONE_COMMIT_LINK} DRONE_REPO_LINK=${DRONE_REPO_LINK} DRONE_BUILD_FINISHED=${DRONE_BUILD_FINISHED} DEBUG='false' OTS_CHAT_LINK=${OTS_CHAT_LINK} ONION_ADDRESS

###########
# BUILDER #
###########
FROM node:16-alpine3.14 AS builder

# pass the global args
ARG COMMUNITY_API_URL
ARG HOST
ARG PORT
ARG MATOMO_SITE_ID OTS_FORM_LINK OTS_CHAT_LINK
ARG TARGET_ENV
ARG DRONE_COMMIT_SHA
ARG DRONE_BUILD_NUMBER
ARG DRONE_BUILD_LINK
ARG DRONE_COMMIT_LINK
ARG DRONE_REPO_LINK
ARG DRONE_BUILD_FINISHED
ARG DEBUG
ARG ONION_ADDRESS

# copy build context and install dependencies
WORKDIR /workspace
COPY . .
RUN npm install

# inject build args as enviroment variables
ENV NODE_ENV=$NODE_ENV HOST=$HOST PORT=$PORT MATOMO_SITE_ID=$MATOMO_SITE_ID OTS_FORM_LINK=$OTS_FORM_LINK TARGET_ENV=${TARGET_ENV} DRONE_COMMIT_SHA=$DRONE_COMMIT_SHA DRONE_BUILD_NUMBER=${DRONE_BUILD_NUMBER} DRONE_BUILD_LINK=${DRONE_BUILD_LINK} DRONE_COMMIT_LINK=${DRONE_COMMIT_LINK} DRONE_REPO_LINK=${DRONE_REPO_LINK} DRONE_BUILD_FINISHED=${DRONE_BUILD_FINISHED} DEBUG=${DEBUG} OTS_CHAT_LINK=${OTS_CHAT_LINK} ONION_ADDRESS=${ONION_ADDRESS}

# build NuxtJS project
RUN npm run build

###########
# PROJECT #
###########
FROM node:16-slim

# pass the global args
ARG COMMUNITY_API_URL
ARG HOST
ARG PORT
ARG USER
ARG MATOMO_SITE_ID OTS_FORM_LINK OTS_CHAT_LINK
ARG TARGET_ENV
ARG DRONE_COMMIT_SHA
ARG DRONE_BUILD_NUMBER
ARG DRONE_BUILD_LINK
ARG DRONE_COMMIT_LINK
ARG DRONE_REPO_LINK
ARG DRONE_BUILD_FINISHED
ARG DEBUG
ARG ONION_ADDRESS

# copy builder output to project workdir
WORKDIR /app
COPY --from=builder --chown=${USER}:${USER} /workspace/.nuxt /app/.nuxt
COPY --from=builder --chown=${USER}:${USER} /workspace/ /app/

# inject build args as enviroment variables
ENV COMMUNITY_API_URL=$COMMUNITY_API_URL HOST=$HOST PORT=$PORT MATOMO_SITE_ID=$MATOMO_SITE_ID OTS_FORM_LINK=$OTS_FORM_LINK TARGET_ENV=${TARGET_ENV} DRONE_COMMIT_SHA=$DRONE_COMMIT_SHA DRONE_BUILD_NUMBER=${DRONE_BUILD_NUMBER} DRONE_BUILD_LINK=${DRONE_BUILD_LINK} DRONE_COMMIT_LINK=${DRONE_COMMIT_LINK} DRONE_REPO_LINK=${DRONE_REPO_LINK} DRONE_BUILD_FINISHED=${DRONE_BUILD_FINISHED} DEBUG=${DEBUG} OTS_CHAT_LINK=${OTS_CHAT_LINK} ONION_ADDRESS=${ONION_ADDRESS}

# set user context
USER ${USER}

# expose port
EXPOSE ${PORT}

# run for production
CMD [ "npm", "run", "start"]
